# Generated by Django 3.1 on 2020-09-05 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='timestamp',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='updated',
            new_name='date_updated',
        ),
    ]
