# Generated by Django 3.1 on 2020-09-06 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
