# Generated by Django 3.1 on 2020-09-07 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200907_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599510920.9048507', max_length=120, unique=True),
        ),
    ]
