# Generated by Django 3.1 on 2020-09-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200907_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599515707.0571241', max_length=120, unique=True),
        ),
    ]
