# Generated by Django 3.1 on 2020-09-08 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_auto_20200907_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599550858.1299102', max_length=120, unique=True),
        ),
    ]
