# Generated by Django 3.1 on 2020-09-08 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200908_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599550891.5082195', max_length=120, unique=True),
        ),
    ]
