# Generated by Django 3.1 on 2020-09-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200908_0846'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599551379.1182358', max_length=120, unique=True),
        ),
    ]
