# Generated by Django 3.1 on 2020-09-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20200908_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599573614.4384906', max_length=120, unique=True),
        ),
    ]
