# Generated by Django 3.0.10 on 2020-09-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20200908_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599576124.6515894', max_length=120, unique=True),
        ),
    ]
