# Generated by Django 3.0.10 on 2020-09-08 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200908_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599578373.1662338', max_length=120, unique=True),
        ),
    ]
