# Generated by Django 3.0.10 on 2020-09-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20200908_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599579031.6836774', max_length=120, unique=True),
        ),
    ]
