# Generated by Django 3.0.10 on 2020-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200908_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599604366.7908092', max_length=120, unique=True),
        ),
    ]
