# Generated by Django 3.0.10 on 2020-09-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200908_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599611091.642692', max_length=120, unique=True),
        ),
    ]
