# Generated by Django 3.0.10 on 2020-09-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200909_0124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599661726.243009', max_length=120, unique=True),
        ),
    ]
