# Generated by Django 3.0.10 on 2020-09-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20200909_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599687624.7398946', max_length=120, unique=True),
        ),
    ]
