# Generated by Django 3.0.10 on 2020-09-09 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_auto_20200909_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599688784.7637641', max_length=120, unique=True),
        ),
    ]
