# Generated by Django 3.0.10 on 2020-09-09 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20200909_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599692914.804321', max_length=120, unique=True),
        ),
    ]
