# Generated by Django 3.0.10 on 2020-09-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200910_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599706421.6509695', max_length=120, unique=True),
        ),
    ]
