# Generated by Django 3.0.10 on 2020-09-10 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20200910_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599707703.9017682', max_length=120, unique=True),
        ),
    ]
