# Generated by Django 3.0.10 on 2020-09-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200910_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599709127.0031583', max_length=120, unique=True),
        ),
    ]
