# Generated by Django 3.0.10 on 2020-09-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_auto_20200910_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='1599736467.2389696', max_length=120, unique=True),
        ),
    ]
