# Generated by Django 3.0.10 on 2020-09-08 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200908_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='email_verify',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='phone_verify',
            field=models.BooleanField(default=False),
        ),
    ]
