# Generated by Django 3.0.10 on 2020-09-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200908_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='phone_code',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
