# Generated by Django 3.0.10 on 2020-09-10 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200910_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='email_verify',
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
